import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function PostPage() {
  const router = useRouter();
  const { post } = router.query;
  const test = [
    { one: "one 1", two: "two 1" },
    { one: "one 2", two: "two 2" },
    { one: "one 3", two: "two 3" },
    { one: "one 4", two: "two 4" },
    { one: "one 5", two: "two 5" },
  ];
  return (
    <>
      <Head>
        <title>Alex School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <main className="px-5 md:px-24 lg:px-48">
        <h1>Post Header {post}</h1>
        <p>{test[Number(post) - 1].one}</p>
      </main>
    </>
  );
}
