import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Teatcher from "../components/teatcher";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import Icon from "../components/icons/icon";

export default function Home() {
  const teatchers = [
    {
      img: "https://lh3.googleusercontent.com/pw/AMWts8AMS0ZMF8MVJJg6p6RhnYtNwB9GP5_BS9U0j1ecwSRYmXMv1olmuBEOH-2DBoVr6-qdQPidU2soqnW-ejCla4LoWHyIWIqnX-8P9OcN2gWbAU6XKXo3tAst8iSqb4WkwEuC6zTQlMXOOpEVPRwbBPeM=w1280-h643-s-no?authuser=0",
      name: "Олександр",
      desc: "Викладач, за плечами якого, не один десяток щасливих студенток та студентів",
    },
    {
      img: "https://lh3.googleusercontent.com/pw/AMWts8AMS0ZMF8MVJJg6p6RhnYtNwB9GP5_BS9U0j1ecwSRYmXMv1olmuBEOH-2DBoVr6-qdQPidU2soqnW-ejCla4LoWHyIWIqnX-8P9OcN2gWbAU6XKXo3tAst8iSqb4WkwEuC6zTQlMXOOpEVPRwbBPeM=w1280-h643-s-no?authuser=0",
      name: "Олексій",
      desc: "Викладач, за плечами якого, не один десяток щасливих студенток та студентів",
    },
    {
      name: "Юлія",
      desc: "Викладач, за плечами якого, не один десяток щасливих студенток та студентів",
    },
    {
      img: "https://lh3.googleusercontent.com/pw/AMWts8AMS0ZMF8MVJJg6p6RhnYtNwB9GP5_BS9U0j1ecwSRYmXMv1olmuBEOH-2DBoVr6-qdQPidU2soqnW-ejCla4LoWHyIWIqnX-8P9OcN2gWbAU6XKXo3tAst8iSqb4WkwEuC6zTQlMXOOpEVPRwbBPeM=w1280-h643-s-no?authuser=0",
      name: "Олександр",
      desc: "Викладач, за плечами якого, не один десяток щасливих студенток та студентів",
    },
    {
      img: "https://lh3.googleusercontent.com/pw/AMWts8AMS0ZMF8MVJJg6p6RhnYtNwB9GP5_BS9U0j1ecwSRYmXMv1olmuBEOH-2DBoVr6-qdQPidU2soqnW-ejCla4LoWHyIWIqnX-8P9OcN2gWbAU6XKXo3tAst8iSqb4WkwEuC6zTQlMXOOpEVPRwbBPeM=w1280-h643-s-no?authuser=0",
      name: "Олександр",
      desc: "Викладач, за плечами якого, не один десяток щасливих студенток та студентів",
    },
    {
      img: "https://lh3.googleusercontent.com/pw/AMWts8AMS0ZMF8MVJJg6p6RhnYtNwB9GP5_BS9U0j1ecwSRYmXMv1olmuBEOH-2DBoVr6-qdQPidU2soqnW-ejCla4LoWHyIWIqnX-8P9OcN2gWbAU6XKXo3tAst8iSqb4WkwEuC6zTQlMXOOpEVPRwbBPeM=w1280-h643-s-no?authuser=0",
      name: "Олександр",
      desc: "Викладач, за плечами якого, не один десяток щасливих студенток та студентів",
    },
  ];

  const feedback = [
    "Юлія Олегівна дуже добра, щира, професіонал своєї справи. Я відвідувала заняття з вересня один раз на тиждень. Задоволена результатом. Багато нового дізналася та вивчила. Уроки не були для мене дуже важкими, але я досягла бажаного результату!Юліє Олегівно, дякую за навчання і за цікаві, різноманітні уроки.Рекомендую кожному для підготовки до ЗНО. Впевнена, що ви також будете задоволені результатом!",
    "Олександр - найліпший вчитель з усіх, яких я коли - не будь знав! Я готувався в нього до ЗНО з математики та фізики, так що, можете бути впевненими, дало свої обіцяні та очікувані результати!) Він навчив мене не лише свого предмету, але і навчив мене працелюбності, зібраності та надихнув мене до вивчення математики та фізики загалом. Олександр, на мою думку, має вроджене почуття розуміння будь-якої людини, тобто, він знаходить підхід абсолютно до всіх, навіть до тих, до кого дуже нелегко «достукатись». Саша дуже цікавий та неймовірний вчитель, який надихає Вас до навчання, з ним Вам буде легко та приємно занурюватися в світ математичних та фізичних наук. Бажаю Вам всього найкращого!)",
    "Рік тому прийшов на курси з рівнeм знань нижчe сeрeднього. Завдяки профі-викладачам — підтягнув знання по шкільним прeдмeтам, отримав не менше 10 балів в аттeстаті та поступив на бюджeт у бажаний унівeрситeт! Усім рeкомeндую саме ці курси, адже, окрім бажаних знань, ви будете проводити час з цікавими і веселими викладачами. Дякую, «Від А до Я», за добре проведений час!",
    "Цього року, я склала іспит ЗНО на 183 бали, а ДПА на 11 балів, і все це завдяки такому чудовому Вчителю, як Олексій. Раніше, я не вивчала математику. І почала її вивчати за три місяці до іспиту. За ці три місяці, Олексій зробив неможливе… Не один вчитель не зможе з нуля, за три місяці, ідеально підготувати учня до іспиту. Але Вам це вдалося!!! Олексію, щиро ДЯКУЮ за неймовірно цікаві та легкi уроки!!! )))",
  ];
  return (
    <>
      <Head>
        <title>Alex School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-5 md:mx-24 lg:mx-48 font-montserrat ">
        <div id="main" className="mt-16 mb-16 md:mb-72">
          <h1 className="text-large mx-auto lg:mx-0 lg:text-xl w-3/4 font-medium leading-tight">
            Онлайн - школа{" "}
            <p className="inline text-mainColor">професійної підготовки</p> до
            НМТ
          </h1>
          <h2 className="text-medium w-3/4 my-16 mx-auto lg:mx-0 lg:text-ml lg:w-2/5">
            Якісна підготовка - гарантує вступ до університету мрії
          </h2>
          <button className="rounded-2xl mx-20 font-medium text-white bg-mainColor text-small p-5 lg:mx-0 md:text-main md:p-7 hover:bg-emerald-500">
            Безкоштовний урок
          </button>
        </div>
        <div
          id="about"
          className="mx-2 mb-16 md:mb-52  flex flex-wrap justify-center"
        >
          <h1 className="text-large text-center w-full inline-block lg:text-xl font-medium leading-tight">
            Про нас
          </h1>
          <h2 className="text-medium text-center w-4/5 my-16 mx-auto lg:mx-0 lg:text-ml ">
            Команда Alex- це <p className="inline text-mainColor">молоді</p> та
            перспективні вчителі. Люди, які самі не так давно були на місці
            учнів, зможуть зацікавити та на прикладах з життя вдало пояснити
            матеріал. Працюючи у цій сфері вже чотири роки, ми пишаємось
            результатами у вигляді задоволених процессом навчання учнів та
            задоволених результатами батьків.
          </h2>
        </div>
        <div
          id="teachers"
          className="mb-16 md:mb-52  flex flex-wrap justify-center"
        >
          <h1 className="text-large inline-block lg:text-xl font-medium  mb-10 md:mb-20 ">
            Викладачі
          </h1>
          <Carousel
            additionalTransfrom={0}
            arrows
            autoPlay
            autoPlaySpeed={5000}
            centerMode={false}
            className=""
            containerClass="container"
            dotListClass=""
            draggable
            focusOnSelect={false}
            infinite={true}
            itemClass=""
            keyBoardControl
            minimumTouchDrag={10}
            pauseOnHover
            renderArrowsWhenDisabled={false}
            renderButtonGroupOutside={false}
            renderDotsOutside={false}
            responsive={{
              desktop: {
                breakpoint: {
                  max: 3000,
                  min: 1024,
                },
                items: 3,
                partialVisibilityGutter: 40,
              },
              mobile: {
                breakpoint: {
                  max: 464,
                  min: 0,
                },
                items: 1,
                partialVisibilityGutter: 30,
              },
              tablet: {
                breakpoint: {
                  max: 1024,
                  min: 464,
                },
                items: 2,
                partialVisibilityGutter: 30,
              },
            }}
            rewind={false}
            rewindWithAnimation={false}
            rtl={false}
            shouldResetAutoplay
            showDots={false}
            sliderClass=""
            slidesToSlide={1}
            swipeable
          >
            {teatchers.map((teatcher, index) => (
              <Teatcher key={index} {...teatcher} />
            ))}
          </Carousel>
        </div>
        <div
          id="services"
          className="mx-2  mb-16 md:mb-52  flex flex-wrap justify-center"
        >
          <h1 className="text-large  inline-block lg:text-xl  font-medium leading-tight">
            Види послуг
          </h1>
          <h2 className="text-medium text-center w-4/5 my-10 md:mt-28 mx-auto lg:mx-0 lg:text-ml ">
            Заняття проводяться виключно на{" "}
            <p className="inline text-mainColor">індивідуальній</p> основі, що
            забезпечує максимально ефективний підхід до навчання. Гнучкий графік
            занять дозволяє погоджувати час та частоту занять з вашим
            репетитором, щоб графік відповідав вашим потребам та можливостям.
          </h2>
          <div className="flex w-4/5 mt-10 justify-around flex-wrap text-small md:text-main">
            <div className="w-full my-4 md:w-2/5 m-2 p-6 shadow-[-4px_4px_10px_2px_rgba(0,0,0,0.25)]">
              <p>
                1-4 клас <br />
                (молодша школа)
              </p>
              <ul className=" marker:text-mainColor list-disc font-medium pl-6 my-11">
                <li className="my-5">1 година - 160грн</li>
                <li className="my-5">
                  Місяць (9 занять) - 1300грн{" "}
                  <Icon
                    icon="shopping-sale"
                    size={20}
                    color={"rgb(61 169 171 )"}
                  />{" "}
                  <p className="inline text-mainColor">-10%</p>
                </li>
              </ul>
            </div>
            <div className="w-full my-4 md:w-2/5 m-2 p-6 shadow-[4px_4px_10px_2px_rgba(0,0,0,0.25)]">
              <p>
                5-9 клас <br />
                (середня школа)
              </p>
              <ul className=" marker:text-mainColor list-disc font-medium pl-6 my-11">
                <li className="my-5">1 година - 190грн</li>
                <li className="my-5">
                  Місяць (9 занять) - 1540грн{" "}
                  <Icon
                    icon="shopping-sale"
                    size={20}
                    color={"rgb(61 169 171 )"}
                  />{" "}
                  <p className="inline text-mainColor">-10%</p>
                </li>
              </ul>
            </div>
            <div className="w-full my-4 md:w-2/5 m-2 p-6  shadow-[0px_10px_10px_-2px_rgba(0,0,0,0.25)]">
              <p>
                10-11 клас <br />
                (старша школа)
              </p>
              <ul className=" marker:text-mainColor list-disc font-medium pl-6 my-11">
                <li className="my-5">1 година - 220грн</li>
                <li className="my-5">
                  Місяць (9 занять) - 1880грн{" "}
                  <Icon
                    icon="shopping-sale"
                    size={20}
                    color={"rgb(61 169 171 )"}
                  />{" "}
                  <p className="inline text-mainColor">-5%</p>
                </li>
              </ul>
            </div>
          </div>
          <h2 className="text-medium text-justify w-4/5 my-10 md:mt-28 mx-auto lg:mx-0 lg:text-ml ">
            Бонусом, надаємо доступ до телеграм каналу з учнями, де публікується
            лише <p className="inline text-mainColor">найнеобхідніша</p>{" "}
            інформація по заданому предмету.
          </h2>
        </div>
        <div id="feedback" className="mx-2 flex flex-wrap mb-32 justify-center">
          <h1 className="text-large w-full text-center inline-block lg:text-xl font-medium text-mainColor">
            Відгуки
          </h1>
          <div className="columns-2  gap-4">
            {feedback.map((item, index) => (
              <p
                key={index}
                className="bg-mainColor text-white w-full mt-0 mr-4 mb-4 ml-0 p-3 rounded-lg box-border inline-block"
              >
                {item}
              </p>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
