import React from "react";
import Head from "next/head";
import Post from "../components/post/post";

export default function Materials() {
  const test = [
    { one: "one 1", two: "two 1" },
    { one: "one 2", two: "two 2" },
    { one: "one 3", two: "two 3" },
    { one: "one 4", two: "two 4" },
    { one: "one 5", two: "two 5" },
  ];
  return (
    <>
      <Head>
        <title>Alex School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <main className="px-5 md:px-24 lg:px-48">
        <div className="flex flex-wrap justify-between">
          {[1, 2, 3, 4, 5].map((item, index) => (
            <div className="mb-8 w-[49%]">
              <Post id={item} info={test[index]} />
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
